import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Landing.module.sass'

export default function Landing() {
  return (
    <div>
      <Head>
        <title>@kpostekk</title>
      </Head>

      <div className={styles.parentContainer}>
        <div className={styles.mainContainer}>
          <div className={styles.mainRow}>
            <h1 className={styles.title}>@kpostekk</h1>
          </div>
          <div className={[styles.mainRow, styles.spacerLine].join(' ')}>
            <div className={styles.sections}>
              <div className={styles.section}>
                <p className={styles.sectionTitle}>Projects</p>
                <div className={styles.sectionHiddenContent}>
                  <p>.awake(that)</p>
                  <p>OpenCore composer</p>
                </div>
              </div>
              <div className={styles.section}>
                <p className={styles.sectionTitle}>Contact</p>
                <div className={styles.sectionHiddenContent}>
                  <p>Email</p>
                  <p>Telegram</p>
                  <p>Discord</p>
                </div>
              </div>
              <div className={styles.section}>
                <a href="#" className={styles.sectionTitle}>Blog</a>
              </div>
              <div className={styles.section}>
                <p className={styles.sectionTitle}>CV</p>
                <div className={styles.sectionHiddenContent}>
                  <a href={'#'}>English 🇬🇧</a>
                  <a href={'#'}>Polski 🇵🇱</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

/* export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
} */
